name: NPM UPDATE

on: 
  schedule:
    - cron: '0 8 * * *' # every day AM 8:00
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm update
    - uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: "npm: Auto update packages"
